plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.ismailidris.pdfreader.fileindex'
version = '0.1.0'

android {
  namespace "com.ismailidris.pdfreader.fileindex"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
  }
  lint {
    abortOnError true
  }
}

dependencies {
  testImplementation 'junit:junit:4.13.2'

  // Same androidx.test versions as expo-modules-core's own instrumented tests.
  androidTestImplementation 'junit:junit:4.13.2'
  androidTestImplementation 'androidx.test:runner:1.7.0'
  androidTestImplementation 'androidx.test:core:1.7.0'
}
